print("My name is Wayne Kareigi")
print("I am 18 years old")
print("I come from Kiambu county")
print("I love swimming, watching and playing football")
print("--------------")
print("**************")
print("##############")